-- Create universities table if it doesn't exist
CREATE TABLE IF NOT EXISTS universities (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  type TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add universities
INSERT INTO universities (name, city, type) VALUES
-- Private Universities
('Lahore University of Management Sciences (LUMS)', 'Lahore', 'Private'),
('Institute of Business Administration (IBA)', 'Karachi', 'Private'),
('National University of Computer and Emerging Sciences (FAST-NUCES)', 'Multiple Cities', 'Private'),
('Iqra University', 'Karachi', 'Private'),
('University of Central Punjab', 'Lahore', 'Private'),
('University of South Asia', 'Lahore', 'Private'),
('University of Management and Technology', 'Lahore', 'Private'),
('University of Lahore', 'Lahore', 'Private'),
('University of Faisalabad', 'Faisalabad', 'Private'),
('University of Gujranwala', 'Gujranwala', 'Private'),
('University of Multan', 'Multan', 'Private'),
('University of Sargodha', 'Sargodha', 'Private'),
('University of Bahawalpur', 'Bahawalpur', 'Private'),
('University of Dera Ghazi Khan', 'Dera Ghazi Khan', 'Private'),
('University of Rahim Yar Khan', 'Rahim Yar Khan', 'Private'),
('University of Muzaffargarh', 'Muzaffargarh', 'Private'),
('University of Bhakkar', 'Bhakkar', 'Private'),
('University of Mianwali', 'Mianwali', 'Private'),
('University of Khushab', 'Khushab', 'Private'),
('University of Attock', 'Attock', 'Private'),
('University of Jhelum', 'Jhelum', 'Private'),
('University of Mandi Bahauddin', 'Mandi Bahauddin', 'Private'),
('University of Hafizabad', 'Hafizabad', 'Private'),
('University of Chiniot', 'Chiniot', 'Private'),
('University of Kasur', 'Kasur', 'Private'),
('University of Sheikhupura', 'Sheikhupura', 'Private'),
('University of Nankana Sahib', 'Nankana Sahib', 'Private'),
('University of Toba Tek Singh', 'Toba Tek Singh', 'Private'),
('University of Pakpattan', 'Pakpattan', 'Private'),
('University of Vehari', 'Vehari', 'Private'),
('University of Lodhran', 'Lodhran', 'Private'),
('University of Bahawalnagar', 'Bahawalnagar', 'Private'),
('University of Khanewal', 'Khanewal', 'Private'),
('University of Layyah', 'Layyah', 'Private'),
('University of Rajanpur', 'Rajanpur', 'Private'),
('University of Kot Addu', 'Kot Addu', 'Private'),
('University of Taunsa', 'Taunsa', 'Private'),
('University of Dera Murad Jamali', 'Dera Murad Jamali', 'Private'),
('University of Zhob', 'Zhob', 'Private'),
('University of Killa Saifullah', 'Killa Saifullah', 'Private'),
('University of Qilla Abdullah', 'Qilla Abdullah', 'Private'),
('University of Panjgur', 'Panjgur', 'Private'),
('University of Nushki', 'Nushki', 'Private'),
('University of Mastung', 'Mastung', 'Private'),
('University of Kalat', 'Kalat', 'Private'),
('University of Kharan', 'Kharan', 'Private'),
('University of Washuk', 'Washuk', 'Private'),
('University of Awaran', 'Awaran', 'Private'),
('University of Kech', 'Kech', 'Private'),
('University of Lasbela', 'Lasbela', 'Private'),
('University of Jiwani', 'Jiwani', 'Private'),
('University of Ormara', 'Ormara', 'Private'),
('University of Pasni', 'Pasni', 'Private'),
('University of Gwadar', 'Gwadar', 'Private'),
('University of Khipro', 'Khipro', 'Private'),
('University of Mithi', 'Mithi', 'Private'),
('University of Umerkot', 'Umerkot', 'Private'),
('University of Tharparkar', 'Tharparkar', 'Private'),
('University of Mirpur Khas', 'Mirpur Khas', 'Private'),
('University of Badin', 'Badin', 'Private'),
('University of Tando Allahyar', 'Tando Allahyar', 'Private'),
('University of Tando Muhammad Khan', 'Tando Muhammad Khan', 'Private'),
('University of Hyderabad', 'Hyderabad', 'Private'),
('University of Sukkur', 'Sukkur', 'Private'),
('University of Larkana', 'Larkana', 'Private'),
('Capital University of Science and Technology', 'Islamabad', 'Private'),
('Riphah International University', 'Islamabad', 'Private'),
('Shifa Tameer-e-Millat University', 'Islamabad', 'Private'),
('Foundation University', 'Islamabad', 'Private'),
('Bahria University', 'Islamabad', 'Private'),
('Hamdard University', 'Karachi', 'Private'),
('Jinnah University for Women', 'Karachi', 'Private'),
('Karachi Institute of Economics and Technology', 'Karachi', 'Private'),
('Preston University', 'Karachi', 'Private'),
('Sir Syed University of Engineering and Technology', 'Karachi', 'Private'),
('Textile Institute of Pakistan', 'Karachi', 'Private'),
('Ziauddin University', 'Karachi', 'Private'),
('Greenwich University', 'Karachi', 'Private'),
('Indus University', 'Karachi', 'Private'),
('Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology (SZABIST)', 'Karachi', 'Private'),
('Baqai Medical University', 'Karachi', 'Private'),
('DHA Suffa University', 'Karachi', 'Private'),
('Habib University', 'Karachi', 'Private'),
('Institute of Business Management (IOBM)', 'Karachi', 'Private'),
('KASB Institute of Technology', 'Karachi', 'Private'),
('Muhammad Ali Jinnah University', 'Karachi', 'Private'),
('Newports Institute of Communications and Economics', 'Karachi', 'Private'),
('Pakistan Air Force-Karachi Institute of Economics and Technology', 'Karachi', 'Private'),
('Sindh Institute of Medical Sciences', 'Karachi', 'Private'),
('Commecs Institute of Business and Emerging Sciences', 'Karachi', 'Private'),
('Dadabhoy Institute of Higher Education', 'Karachi', 'Private'),
('Institute of Clinical Psychology', 'Karachi', 'Private'),
('Isra University', 'Hyderabad', 'Private'),
('Liaquat University of Medical and Health Sciences', 'Jamshoro', 'Private'),
('Shaheed Benazir Bhutto University', 'Nawabshah', 'Private'),
('Al-Khair University', 'Bhimber', 'Private'),
('University of Management and Technology', 'Sialkot', 'Private'),
('Beaconhouse National University', 'Lahore', 'Private'),
('Forman Christian College', 'Lahore', 'Private'),

-- Military Universities
('National Defence University', 'Islamabad', 'Military'),
('Air University', 'Islamabad', 'Military'),
('Pakistan Naval Academy', 'Karachi', 'Military'),
('Military College of Signals', 'Rawalpindi', 'Military'),
('College of Electrical and Mechanical Engineering', 'Rawalpindi', 'Military'),
('Military College of Engineering', 'Risalpur', 'Military'),
('Army Medical College', 'Rawalpindi', 'Military');

-- Enable row-level security
ALTER TABLE universities ENABLE ROW LEVEL SECURITY;

-- Create policy for public access
DROP POLICY IF EXISTS "Public access" ON universities;
CREATE POLICY "Public access"
ON universities FOR SELECT
USING (true);

-- Enable realtime
alter publication supabase_realtime add table universities;
